apiVersion: v1
kind: ReactionProvider
name: Advanced
spec:
  services:
    reaction:
      image: reaction-advanced
      externalImage: true
  config_schema:
    type: object
    properties: 
      MyConnectionString:
        type: string
    required:
      - MyConnectionString
