kind: Reaction
apiVersion: v1
name: post-dapr-pubsub
spec:
  kind: PostDaprPubSub
  properties:
    # No global properties needed for this reaction
  queries:
    example-query: |
      {
        "pubsubName": "drasi-pubsub",
        "topicName": "example-topic",
        "packed": false,
        "skipControlSignals": false
      }
    another-query: |
      {
        "pubsubName": "messaging",
        "topicName": "data-updates",
        "packed": true,
        "skipControlSignals": false
      }
    control-signals-skipped: |
      {
        "pubsubName": "drasi-pubsub",
        "topicName": "changes-only",
        "packed": false,
        "skipControlSignals": true
      }
    templated-query: |
      {
        "pubsubName": "drasi-pubsub",
        "topicName": "custom-events",
        "addedResultsTemplate": "{\"event\": \"created\", \"id\": \"{{id}}\", \"name\": \"{{name}}\" }",
        "updatedResultsTemplate": "{\"event\": \"modified\", \"id\": \"{{after.id}}\", \"oldName\": \"{{before.name}}\", \"newName\": \"{{after.name}}\" }",
        "deletedResultsTemplate": "{\"event\": \"removed\", \"id\": \"{{id}}\" }"
      }