# generated by datamodel-codegen:
#   filename:  AgentDelivery.json

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import BaseModel, ConfigDict, Field, StrictStr

from .DeleteEvent import DeleteEvent
from .InsertEvent import InsertEvent
from .UpdateEvent import UpdateEvent


class AgentDelivery(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schemaVersion: Literal[1]
    routerId: Annotated[
        StrictStr, Field(min_length=1, pattern='^[^/\\s]+/[^/\\s]+$', title='RouterId')
    ]
    subscriptionIncarnation: Annotated[
        StrictStr, Field(min_length=1, title='NonEmptyString')
    ]
    eventId: Annotated[StrictStr, Field(min_length=1, title='NonEmptyString')]
    event: InsertEvent | UpdateEvent | DeleteEvent
