# generated by datamodel-codegen:
#   filename:  InsertPayload.json

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, ConfigDict

from .ChangeSource import ChangeSource


class InsertPayload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    source: ChangeSource
    after: dict[str, Any]
