# generated by datamodel-codegen:
#   filename:  ListQueriesRequest.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class ListQueriesRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
