# generated by datamodel-codegen:
#   filename:  Query.json

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field, StrictStr


class Query(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    query_id: Annotated[StrictStr, Field(min_length=1, title='NonEmptyString')]
    title: Annotated[StrictStr, Field(min_length=1, title='NonEmptyString')]
    description: Annotated[StrictStr, Field(min_length=1, title='NonEmptyString')]
    usage: Annotated[StrictStr | None, Field(min_length=1, title='NonEmptyString')] = (
        None
    )
