# generated by datamodel-codegen:
#   filename:  Subscriber.json

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field, StrictStr


class Subscriber(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    namespace: Annotated[
        StrictStr, Field(min_length=1, pattern='^[^/\\s]+$', title='IdentityPart')
    ]
    app_id: Annotated[
        StrictStr, Field(min_length=1, pattern='^[^/\\s]+$', title='IdentityPart')
    ]
    agent_name: Annotated[StrictStr, Field(min_length=1, title='NonEmptyString')]
