# generated by datamodel-codegen:
#   filename:  SubscribeResponse.json

from __future__ import annotations

from enum import Enum
from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field, StrictStr

from .Operation import Operation


class Status(Enum):
    created = 'created'
    updated = 'updated'


class SubscribeResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    query_id: Annotated[StrictStr, Field(min_length=1, title='NonEmptyString')]
    operations: Annotated[
        list[Operation],
        Field(
            description='Selected operations in canonical i, u, d order; enforced by the protocol boundary helpers.',
            max_length=3,
            min_length=1,
        ),
    ]
    subscription_incarnation: Annotated[
        StrictStr, Field(min_length=1, title='NonEmptyString')
    ]
    topic_name: Annotated[StrictStr, Field(min_length=1, title='NonEmptyString')]
    status: Status
