# generated by datamodel-codegen:
#   filename:  ToolError.json

from __future__ import annotations

from enum import Enum
from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field, StrictStr


class Code(Enum):
    invalid_arguments = 'invalid_arguments'
    unknown_query = 'unknown_query'
    incarnation_conflict = 'incarnation_conflict'
    state_unavailable = 'state_unavailable'


class ToolError(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    code: Code
    message: Annotated[StrictStr, Field(min_length=1, title='NonEmptyString')]
