# generated by datamodel-codegen:
#   filename:  UnsubscribeRequest.json

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field, StrictStr

from .Subscriber import Subscriber


class UnsubscribeRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    query_id: Annotated[StrictStr, Field(min_length=1, title='NonEmptyString')]
    subscriber: Subscriber
    subscription_incarnation: Annotated[
        StrictStr, Field(min_length=1, title='NonEmptyString')
    ]
