# generated by datamodel-codegen:
#   filename:  UpdateEvent.json

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import BaseModel, ConfigDict, Field, StrictInt

from .UpdatePayload import UpdatePayload


class UpdateEvent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    seq: Annotated[StrictInt, Field(ge=0, title='Sequence')]
    ts_ms: Annotated[StrictInt, Field(ge=0, title='Timestamp')]
    op: Literal['u']
    payload: UpdatePayload
