kind: ContinuousQuery
apiVersion: v1
name: quick-query
spec:
  mode: query
  sources:
    subscriptions:
      - id: quick-test
  query: >
    MATCH
      (i:Item {category: 'A'})
    RETURN
      i.id as Id,
      i.name as Name,
      i.category as Category