apiVersion: v1
kind: Source
name: quick-test
spec:
  kind: PostgreSQL
  properties:
    host: postgres.default.svc.cluster.local
    user: postgres
    port: 5432
    ssl: false
    password: smoke-test
    database: smokedb
    tables:
      - public.Item