FROM rust@sha256:c50cd6e20c46b0b36730b5eb27289744e4bb8f32abc90d8c64ca09decf4f55ba as builder
# rust:1.81-bullseye
RUN apt-get update && apt-get install -y protobuf-compiler libcurl4 && apt-get clean

WORKDIR /usr/src
COPY . .
WORKDIR /usr/src
RUN cargo install --force --path .

FROM ubuntu:22.04 as final
RUN apt-get update && apt-get install -y openssl bash curl libssl3  && rm -rf /var/lib/apt/lists/*
# gcr.io/distroless/cc-debian11
ENV RUST_BACKTRACE=1
COPY --from=builder /usr/local/cargo/bin/kubernetes-reactivator /usr/local/bin/kubernetes-reactivator
CMD ["kubernetes-reactivator"]