# Copyright 2024 The Drasi Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: drasi-resource-provider
  labels:
    drasi/infra: resource-provider
spec:
  replicas: 1
  selector:
    matchLabels:
      drasi/infra: resource-provider
  template:
    metadata:
      annotations:
        dapr.io/app-id: resource-provider
        dapr.io/config: dapr-config
        dapr.io/app-port: "8080"
        dapr.io/enabled: "true"
        dapr.io/sidecar-image: %DAPRD_VERSION%
      labels:
        drasi/infra: resource-provider
    spec:
      priorityClassName: drasi-infrastructure
      serviceAccountName: drasi-resource-provider
      containers:
        - name: kubernetes-provider
          imagePullPolicy: %IMAGE_PULL_POLICY%
          image: %ACR%drasi-project/kubernetes-provider:%TAG%
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: ACR
              valueFrom:
                configMapKeyRef:
                  name: drasi-config
                  key: ACR
                  optional: true
            - name: IMAGE_VERSION_TAG
              valueFrom:
                configMapKeyRef:
                  name: drasi-config
                  key: IMAGE_VERSION_TAG
                  optional: true
            - name: IMAGE_PULL_POLICY
              valueFrom:
                configMapKeyRef:
                  name: drasi-config
                  key: IMAGE_PULL_POLICY
                  optional: true
            - name: DAPR_CONFIG
              valueFrom:
                configMapKeyRef:
                  name: drasi-config
                  key: DAPR_CONFIG
                  optional: true
            - name: DAPR_SIDECAR
              valueFrom:
                configMapKeyRef:
                  name: drasi-config
                  key: DAPR_SIDECAR
                  optional: true
            - name: INGRESS_CLASS_NAME
              valueFrom:
                configMapKeyRef:
                  name: drasi-config
                  key: INGRESS_CLASS_NAME
                  optional: true
            - name: INGRESS_LOAD_BALANCER_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: drasi-config
                  key: INGRESS_LOAD_BALANCER_SERVICE
                  optional: true
            - name: INGRESS_LOAD_BALANCER_NAMESPACE
              valueFrom:
                configMapKeyRef:
                  name: drasi-config
                  key: INGRESS_LOAD_BALANCER_NAMESPACE
                  optional: true
          resources:
            limits:
              cpu: 200m
            requests:
              cpu: 50m
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: FallbackToLogsOnError
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drasi-api
  labels:
    drasi/infra: api
spec:
  replicas: 1
  selector:
    matchLabels:
      drasi/infra: api
  template:
    metadata:
      annotations:
        dapr.io/app-id: api
        dapr.io/config: dapr-config
        dapr.io/app-port: "8080"
        dapr.io/enabled: "true"
        dapr.io/sidecar-image: %DAPRD_VERSION%
      labels:
        drasi/infra: api
    spec:
      priorityClassName: drasi-infrastructure
      containers:
        - name: drasi-api
          imagePullPolicy: %IMAGE_PULL_POLICY%
          image: %ACR%drasi-project/api:%TAG%
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MONGO_URI
              value: mongodb://drasi-mongo:27017
          ports:
            - containerPort: 8080
              name: api
          resources:
            limits:
              cpu: 200m
            requests:
              cpu: 50m
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: FallbackToLogsOnError
---
apiVersion: v1
kind: Service
metadata:
  name: drasi-api
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      name: api
  selector:
    drasi/infra: api