# Copyright 2024 The Drasi Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: ReactionProvider
name: Debug
spec:
  services:
    reaction:
      image: reaction-debug
      endpoints:
        gateway:
          setting: internal
          target: $portConfigKey
      config_schema:
        type: object
        properties:
          portConfigKey:
            type: number
            default: 8080
---
apiVersion: v1
kind: ReactionProvider
name: Debezium
spec:
  services:
    reaction:
      image: reaction-debezium
  config_schema:
    type: object
    properties: 
      brokers:
        type: array
      topic:
        type: string
      saslUsername:
        type: string
      saslPassword:
        type: string
    required:
      - brokers
      - topic
---
apiVersion: v1
kind: ReactionProvider
name: EventGrid
spec:
  services:
    reaction:
      image: reaction-eventgrid
  config_schema:
    type: object
    properties: 
      eventGridUri:
        type: string
      eventGridKey:
        type: string
      eventGridSchema:
        type: string
        enum:
          - "CloudEvents"
          - "EventGrid"
        default: "CloudEvents"
      format:
        type: string
        enum:
          - "packed"
          - "unpacked"
        default: "packed"
    required:
      - eventGridUri
---
apiVersion: v1
kind: ReactionProvider
name: EventBridge
spec:
  services:
    reaction:
      image: reaction-eventbridge
  config_schema:
    type: object
    properties: 
      eventBusName:
        type: string
        default: "default"
      format:
        type: string
        enum:
          - "packed"
          - "unpacked"
          - "template"
        default: "packed"
---
apiVersion: v1
kind: ReactionProvider
name: Gremlin
spec:
  config_schema:
    type: object
    properties: 
      addedResultCommand:
        type: string
      updatedResultCommand: 
        type: string
      deletedResultCommand:
        type: string
      gremlinHost:
        type: string
      gremlinPort:
        type: number
      gremlinPassword:
        type: string
      gremlinUsername:
        type: string
    required:
      - gremlinHost
      - gremlinPort 
  services:
    reaction:
      image: reaction-gremlin
---
apiVersion: v1
kind: ReactionProvider
name: Result
spec:
  services:
    reaction:
      image: reaction-result
      dapr: 
        app-port: "8080"
      endpoints:
        gateway:
          setting: internal
          target: $result-portConfigKey
      config_schema:
        type: object
        properties:
          result-portConfigKey:
            type: number
            default: 8080
  config_schema:
    type: object
    properties: 
      QueryContainerId:
        type: string
---
apiVersion: v1
kind: ReactionProvider
name: SignalR
spec:
  services:
    reaction:
      image: reaction-signalr
      endpoints:
        gateway:
          setting: external
          target: $signalr-portConfigKey
      config_schema:
        type: object
        properties: 
          signalr-portConfigKey:
            type: number
            default: 8080
  config_schema:
    type: object
    properties:
      connectionString:
        type: string

---
apiVersion: v1
kind: ReactionProvider
name: StorageQueue
spec:
  services:
    reaction:
      image: reaction-storage-queue
  config_schema:
    type: object
    properties:
      endpoint:
        type: string
      queueName:
        type: string
      format:
        type: string
        enum:
          - "packed"
          - "unpacked"
          - "template"
        default: "packed"
    required:
      - queueName
---
apiVersion: v1
kind: ReactionProvider
name: StoredProc
spec:
  config_schema: 
    type: object
    properties: 
      addedResultCommand:
        type: string
      updatedResultCommand:
        type: string
      deletedResultCommand:
        type: string
      databaseHostname:
        type: string
      databasePort:
        type: number
      databaseUser:
        type: string
      databaseDbname:
        type: string
      databasePassword:
        type: string
      databaseClient:
        type: string
      databaseSsl:
        type: boolean
        default: false
    required:
      - databaseHostname
      - databasePort
      - databaseUser
      - databaseDbname
      - databaseClient
      - databasePassword
  services:
    reaction:
      image: reaction-storedproc
---
apiVersion: v1
kind: ReactionProvider
name: Dataverse
spec:
  services:
    reaction:
      image: reaction-dataverse
  config_schema:
    type: object
    properties:
      endpoint:
        type: string
      clientId:
        type: string
      secret:
        type: string
    required:
      - endpoint
      - clientId
      - secret
---
apiVersion: v1
kind: ReactionProvider
name: SyncDaprStateStore
spec:
  services:
    reaction:
      image: reaction-sync-dapr-statestore
---
apiVersion: v1
kind: ReactionProvider
name: PostDaprPubSub
spec:
  services:
    reaction:
      image: reaction-post-dapr-pubsub
---
apiVersion: v1
kind: ReactionProvider
name: Http
spec:
  services:
    reaction:
      image: reaction-http
  config_schema:
    type: object
    properties: 
      baseUrl:
        type: string
      token:
        type: string
      timeout:
        type: number      
    required:
      - baseUrl
---
apiVersion: v1
kind: ReactionProvider
name: MCP
spec:
  services:
    reaction:
      image: reaction-mcp
      endpoints:
        gateway:
          setting: internal
          target: $port
      config_schema:
        type: object
        properties: 
          port:
            type: number
            default: 3000
---
apiVersion: v1
kind: ReactionProvider
name: SyncVectorStore
spec:
  services:
    reaction:
      image: reaction-sync-vectorstore
  config_schema:
    type: object
    properties:
      # Vector Store Configuration
      vectorStoreType:
        type: string
        enum: ["Qdrant", "AzureAISearch", "InMemory"]
        description: "Type of vector store to sync with (currently supported stores)"
      connectionString:
        type: string
        description: "Connection string for the vector store (e.g., 'Endpoint=host:port;ApiKey=key' for Qdrant, 'Endpoint=https://...;ApiKey=key' for Azure AI Search)"
      
      # Embedding Service Configuration
      embeddingServiceType:
        type: string
        enum: ["AzureOpenAI"]
        description: "Type of embedding service to use"
      embeddingEndpoint:
        type: string
        description: "Endpoint URL for the embedding service"
      embeddingApiKey:
        type: string
        description: "API key for the embedding service"
      embeddingModel:
        type: string
        description: "Model name/deployment name for embeddings"
        default: "text-embedding-3-large"
      embeddingDimensions:
        type: integer
        description: "Number of dimensions for embedding vectors"
        default: 3072
        minimum: 1
        maximum: 20000
      
      # Vector Store Collection Configuration
      distanceFunction:
        type: string
        enum: ["CosineSimilarity", "CosineDistance", "EuclideanDistance", "DotProductSimilarity", "ManhattanDistance"]
        description: "Distance function for vector similarity"
        default: "CosineSimilarity"
      indexKind:
        type: string
        enum: ["Hnsw", "Flat", "IvfFlat", "DiskAnn"]
        description: "Index type for vector search"
        default: "Hnsw"
      isFilterable:
        type: boolean
        description: "Enable filtering on data fields"
        default: true
      isFullTextSearchable:
        type: boolean
        description: "Enable full-text search on content fields (Azure AI Search only)"
        default: false
    required:
      - vectorStoreType
      - connectionString
      - embeddingServiceType
      - embeddingEndpoint
      - embeddingApiKey
      - embeddingModel