# Copyright 2024 The Drasi Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: SourceProvider
name: PostgreSQL
spec:
  services:
    proxy:
      image: source-sql-proxy
      dapr:
        app-port: "4002"
      config_schema:
        type: object
        properties:
          client:
            type: string
            default: pg
    reactivator: 
      image: source-debezium-reactivator
      deprovisionHandler: true
      dapr:
        app-port: "80"
      config_schema:
        type: object
        properties:
          connector:
            type: string
            default: PostgreSQL
  config_schema:
    type: object
    properties:
      database:
        type: string
      host:
        type: string
      password:
        type: string
      port:
        type: number
      ssl:
        type: boolean
        default: false
      user:
        type: string
      tables:
        type: array
    required:
      - database
      - host
      - port
      - password
      - user
      - tables
---
apiVersion: v1
kind: SourceProvider
name: SQLServer
spec: 
  services:
    proxy:
      image: source-sql-proxy
      dapr:
        app-port: "4002"
      config_schema:
        type: object
        properties:
          client:
            type: string
            default: mssql
    reactivator: 
      image: source-debezium-reactivator
      deprovisionHandler: true
      dapr:
        app-port: "80"
      config_schema:
        type: object
        properties:
          connector:
            type: string
            default: SQLServer
  config_schema:
    type: object
    properties:
      database:
        type: string
      host:
        type: string
      password:
        type: string
      port:
        type: number
      encrypt:
        type: boolean
        default: false
      user:
        type: string
      tables:
        type: array
    required:
      - database
      - host
      - port
      - password
      - user
      - tables
---
apiVersion: v1
kind: SourceProvider
name: CosmosGremlin
spec: 
  config_schema:
    type: object
    properties:
      accountEndpoint:
        type: string
      database:
        type: string
      container:
        type: string
    required: 
      - accountEndpoint
      - database
      - container
  services:
    proxy:
      image: source-gremlin-proxy
      dapr:
        app-port: "4002"
    reactivator:
      image: source-cosmosdb-reactivator
      config_schema:
        type: object
        properties:
          partitionKey:
            type: string
        required:
          - partitionKey
---
apiVersion: v1
kind: SourceProvider
name: Dataverse
spec: 
  services:
    proxy:
      image: source-dataverse-proxy
      dapr:
        app-port: "80"
    reactivator: 
      image: source-dataverse-reactivator
  config_schema:
    type: object
    properties:
      endpoint:
        type: string
      clientId:
        type: string
      secret:
        type: string
      entities:
        type: array
      interval:
        type: integer
        default: 60
    required:
      - endpoint
      - clientId
      - secret
      - entities
---
apiVersion: v1
kind: SourceProvider
name: EventHub
spec: 
  services:
    proxy:
      image: source-eventhub-proxy
      dapr:
        app-port: "80"
    reactivator: 
      image: source-eventhub-reactivator
  config_schema:
    type: object
    properties:
      connectionString:
        type: string
      consumerGroup:
        type: string
        default: "$Default"
      eventHubs:
        type: array
      bootstrapWindow:
        type: integer
        default: 0
    required:
      - connectionString
      - eventHubs
