# Copyright 2024 The Drasi Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: ReactionProvider
name: Debug
spec:
  services:
    reaction:
      image: reaction-debug
      endpoints:
        gateway:
          setting: internal
          target: $portConfigKey
      config_schema:
        type: object
        properties:
          portConfigKey:
            type: number
            default: 8080
---
apiVersion: v1
kind: ReactionProvider
name: Debezium
spec:
  services:
    reaction:
      image: reaction-debezium
  config_schema:
    type: object
    properties: 
      brokers:
        type: array
      topic:
        type: string
      saslUsername:
        type: string
      saslPassword:
        type: string
    required:
      - brokers
      - topic
---
apiVersion: v1
kind: ReactionProvider
name: EventGrid
spec:
  services:
    reaction:
      image: reaction-eventgrid
  config_schema:
    type: object
    properties: 
      eventGridUri:
        type: string
      eventGridKey:
        type: string
      eventGridSchema:
        type: string
        enum:
          - "CloudEvents"
          - "EventGrid"
        default: "CloudEvents"
      format:
        type: string
        enum:
          - "packed"
          - "unpacked"
        default: "packed"
    required:
      - eventGridUri
---
apiVersion: v1
kind: ReactionProvider
name: Gremlin
spec:
  config_schema:
    type: object
    properties: 
      addedResultCommand:
        type: string
      updatedResultCommand: 
        type: string
      deletedResultCommand:
        type: string
      gremlinHost:
        type: string
      gremlinPort:
        type: number
      gremlinPassword:
        type: string
      gremlinUsername:
        type: string
    required:
      - gremlinHost
      - gremlinPort 
  services:
    reaction:
      image: reaction-gremlin
---
apiVersion: v1
kind: ReactionProvider
name: Result
spec:
  services:
    reaction:
      image: reaction-result
      dapr:
        app-port: "8080"
      endpoints:
        gateway:
          setting: internal
          target: $result-portConfigKey
      config_schema:
        type: object
        properties:
          result-portConfigKey:
            type: number
            default: 8080
  config_schema:
    type: object
    properties: 
      QueryContainerId:
        type: string
---
apiVersion: v1
kind: ReactionProvider
name: SignalR
spec:
  services:
    reaction:
      image: reaction-signalr
      endpoints:
        gateway:
          setting: internal
          target: $signalr-portConfigKey
      config_schema:
        type: object
        properties: 
          signalr-portConfigKey:
            type: number
            default: 8080
  config_schema:
    type: object
    properties:
      connectionString:
        type: string

---
apiVersion: v1
kind: ReactionProvider
name: StorageQueue
spec:
  services:
    reaction:
      image: reaction-storage-queue
  config_schema:
    type: object
    properties:
      endpoint:
        type: string
      queueName:
        type: string
      format:
        type: string
        enum:
          - "packed"
          - "unpacked"
        default: "packed"
    required:
      - queueName
---
apiVersion: v1
kind: ReactionProvider
name: StoredProc
spec:
  config_schema: 
    type: object
    properties: 
      addedResultCommand:
        type: string
      updatedResultCommand:
        type: string
      deletedResultCommand:
        type: string
      databaseHostname:
        type: string
      databasePort:
        type: number
      databaseUser:
        type: string
      databaseDbname:
        type: string
      databasePassword:
        type: string
      databaseClient:
        type: string
      databaseSsl:
        type: boolean
        default: false
    required:
      - databaseHostname
      - databasePort
      - databaseUser
      - databaseDbname
      - databaseClient
      - databasePassword
  services:
    reaction:
      image: reaction-storedproc
---
apiVersion: v1
kind: ReactionProvider
name: Dataverse
spec:
  services:
    reaction:
      image: reaction-dataverse
  config_schema:
    type: object
    properties:
      endpoint:
        type: string
      clientId:
        type: string
      secret:
        type: string
    required:
      - endpoint
      - clientId
      - secret
