apiVersion: v1
kind: SourceProvider
name: PostgreSQL
spec:
  services:
    proxy:
      image: source-sql-proxy
      dapr:
        app-port: "4002"
      config_schema:
        type: object
        properties:
          client:
            type: string
            default: pg
    reactivator: 
      image: source-debezium-reactivator
      deprovisionHandler: true
      dapr:
        app-port: "80"
      config_schema:
        type: object
        properties:
          connector:
            type: string
            default: PostgreSQL
  config_schema:
    type: object
    properties:
      database:
        type: string
      host:
        type: string
      password:
        type: string
      port:
        type: number
      ssl:
        type: boolean
        default: false
      user:
        type: string
      tables:
        type: array
    required:
      - database
      - host
      - port
      - password
      - user
      - tables
---
apiVersion: v1
kind: SourceProvider
name: SQLServer
spec: 
  services:
    proxy:
      image: source-sql-proxy
      dapr:
        app-port: "4002"
      config_schema:
        type: object
        properties:
          client:
            type: string
            default: mssql
    reactivator: 
      image: source-debezium-reactivator
      deprovisionHandler: true
      dapr:
        app-port: "80"
      config_schema:
        type: object
        properties:
          connector:
            type: string
            default: SQLServer
  config_schema:
    type: object
    properties:
      database:
        type: string
      host:
        type: string
      password:
        type: string
      port:
        type: number
      encrypt:
        type: boolean
        default: false
      user:
        type: string
      tables:
        type: array
    required:
      - database
      - host
      - port
      - password
      - user
      - tables
---
apiVersion: v1
kind: SourceProvider
name: CosmosGremlin
spec: 
  config_schema:
    type: object
    properties:
      accountEndpoint:
        type: string
      database:
        type: string
      container:
        type: string
    required: 
      - accountEndpoint
      - database
      - container
  services:
    proxy:
      image: source-gremlin-proxy
      dapr:
        app-port: "4002"
    reactivator:
      image: source-cosmosdb-reactivator
      config_schema:
        type: object
        properties:
          partitionKey:
            type: string
        required:
          - partitionKey