apiVersion: v1
kind: ServiceAccount
metadata:
  name: drasi-resource-provider
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: drasi-resource-provider-role
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - create
      - delete
      - get
      - list
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - persistentvolumeclaims
    verbs:
      - create
      - delete
      - get
      - list
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - create
      - delete
      - get
      - list
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - create
      - delete
      - get
      - list
      - update
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments/status
    verbs:
      - get
  - apiGroups:
      - "dapr.io"
    resources:
      - components
    verbs:
      - create
      - delete
      - get
      - list
      - update
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: drasi-resource-provider-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: drasi-resource-provider-role
subjects:
  - kind: ServiceAccount
    name: drasi-resource-provider