apiVersion: v1
kind: ConfigMap
metadata:
  name: test-data-init
data:
  init.sql: >
    CREATE TABLE public."item" (
        id INTEGER NOT NULL PRIMARY KEY,
        name CHARACTER VARYING(100) NOT NULL,
        category CHARACTER VARYING(10) NOT NULL
    );
    INSERT INTO public."item" (id, name, category)
      VALUES
        (1, 'Item 1', 'A'),
        (2, 'Item 2', 'B'),
        (3, 'Item 3', 'A');
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-pg-config
  labels:
    app: postgres
data:
  POSTGRES_DB: smokedb
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: smoke-test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          args: ["-c", "wal_level=logical"]
          volumeMounts:
          - name: init
            mountPath: "/docker-entrypoint-initdb.d"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: test-pg-config
      volumes:
        - name: init
          configMap:
            name: test-data-init
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  type: ClusterIP
  ports:
   - port: 5432
  selector:
   app: postgres