# generated by datamodel-codegen:
#   filename:  BootstrapCompletedSignal.yaml
#   timestamp: 2026-07-15T18:09:33+00:00

from __future__ import annotations

from typing import Literal

from .ControlSignal import ControlSignal


class BootstrapCompletedSignal(ControlSignal):
    kind: Literal['bootstrapCompleted']
