# generated by datamodel-codegen:
#   filename:  BootstrapStartedSignal.yaml
#   timestamp: 2024-11-22T20:54:00+00:00

from __future__ import annotations

from typing import Literal

from .ControlSignal import ControlSignal


class BootstrapStartedSignal(ControlSignal):
    kind: Literal['bootstrapStarted']
