# generated by datamodel-codegen:
#   filename:  ChangeSource.yaml
#   timestamp: 2026-07-15T18:09:34+00:00

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, Field


class ChangeSource(BaseModel):
    queryId: Annotated[
        str, Field(description='The ID of the query that the change originated from')
    ]
    ts_ms: int
