# generated by datamodel-codegen:
#   filename:  ChangeEvent.yaml
#   timestamp: 2024-11-22T20:54:00+00:00

from __future__ import annotations

from typing import Any, Dict, List, Literal, Optional

from pydantic import Field, RootModel
from typing_extensions import Annotated

from .ResultEvent import ResultEvent
from .UpdatePayload import UpdatePayload


class RecordUnknown(RootModel[Optional[Dict[str, Any]]]):
    root: Optional[Dict[str, Any]] = None


class ChangeEvent(ResultEvent):
    kind: Literal["change"]
    addedResults: Annotated[
        List[RecordUnknown],
        Field(
            description="The results that were added to the result set as a consequence of the change"
        ),
    ]
    updatedResults: Annotated[
        List[UpdatePayload],
        Field(
            description="The results that were updated on the result set as a consequence of the change"
        ),
    ]
    deletedResults: Annotated[
        List[RecordUnknown],
        Field(
            description="The results that were deleted from the result set as a consequence of the change"
        ),
    ]
