# generated by datamodel-codegen:
#   filename:  ChangeNotification.yaml
#   timestamp: 2026-07-15T18:09:34+00:00

from __future__ import annotations

from enum import Enum
from typing import Annotated

from pydantic import Field

from .ChangePayload import ChangePayload
from .Notification import Notification


class Op(Enum):
    i = 'i'
    u = 'u'
    d = 'd'


class ChangeNotification(Notification):
    op: Op
    payload: ChangePayload
    seq: Annotated[int, Field(description='The sequence number of the source change')]
