# generated by datamodel-codegen:
#   filename:  ChangeEvent.yaml
#   timestamp: 2026-07-15T18:09:33+00:00

from __future__ import annotations

from typing import Annotated, Any, Literal

from pydantic import Field, RootModel

from .ResultEvent import ResultEvent
from .UpdatePayload import UpdatePayload


class RecordUnknown(RootModel[dict[str, Any]]):
    root: dict[str, Any]


class ChangeEvent(ResultEvent):
    kind: Literal['change']
    addedResults: Annotated[
        list[RecordUnknown],
        Field(
            description='The results that were added to the result set as a consequence of the change'
        ),
    ]
    updatedResults: Annotated[
        list[UpdatePayload],
        Field(
            description='The results that were updated on the result set as a consequence of the change'
        ),
    ]
    deletedResults: Annotated[
        list[RecordUnknown],
        Field(
            description='The results that were deleted from the result set as a consequence of the change'
        ),
    ]
