# generated by datamodel-codegen:
#   filename:  ControlSignal.yaml
#   timestamp: 2024-11-22T20:54:00+00:00

from __future__ import annotations

from pydantic import BaseModel


class ControlSignal(BaseModel):
    kind: str
