# generated by datamodel-codegen:
#   filename:  ControlPayload.yaml
#   timestamp: 2026-07-15T18:09:34+00:00

from __future__ import annotations

from pydantic import BaseModel

from .ChangeSource import ChangeSource


class ControlPayload(BaseModel):
    source: ChangeSource
    kind: str
