# generated by datamodel-codegen:
#   filename:  ControlSignal.yaml
#   timestamp: 2026-07-15T18:09:33+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel


class Kind(Enum):
    bootstrapStarted = 'bootstrapStarted'
    bootstrapCompleted = 'bootstrapCompleted'
    running = 'running'
    stopped = 'stopped'
    deleted = 'deleted'


class ControlSignal(BaseModel):
    kind: Kind
