# generated by datamodel-codegen:
#   filename:  ControlEvent.yaml
#   timestamp: 2024-11-22T20:54:00+00:00

from __future__ import annotations

from typing import Literal

from .ControlSignal import ControlSignal
from .ResultEvent import ResultEvent


class ControlEvent(ResultEvent):
    kind: Literal["control"]
    controlSignal: ControlSignal
