# generated by datamodel-codegen:
#   filename:  Data.yaml
#   timestamp: 2024-11-22T20:54:01+00:00

from __future__ import annotations

from typing import Any, Dict, Optional

from pydantic import BaseModel, RootModel


class RecordUnknown(RootModel[Optional[Dict[str, Any]]]):
    root: Optional[Dict[str, Any]] = None


class Data(BaseModel):
    data: RecordUnknown
