# generated by datamodel-codegen:
#   filename:  Data.yaml
#   timestamp: 2026-07-15T18:09:33+00:00

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, RootModel


class RecordUnknown(RootModel[dict[str, Any]]):
    root: dict[str, Any]


class Data(BaseModel):
    data: RecordUnknown
