# generated by datamodel-codegen:
#   filename:  Header.yaml
#   timestamp: 2026-07-15T18:09:33+00:00

from __future__ import annotations

from pydantic import BaseModel

from .HeaderItem import HeaderItem


class Header(BaseModel):
    header: HeaderItem
