# generated by datamodel-codegen:
#   filename:  HeaderItem.yaml
#   timestamp: 2026-07-15T18:09:33+00:00

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, Field


class HeaderItem(BaseModel):
    sequence: Annotated[int, Field(description='The sequence number of the event')]
    timestamp: Annotated[
        int, Field(description='The time at which the source change was recorded')
    ]
    state: str | None = None
