# generated by datamodel-codegen:
#   filename:  Notification.yaml
#   timestamp: 2026-07-15T18:09:34+00:00

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, RootModel

from .Op import Op


class RecordUnknown(RootModel[dict[str, Any]]):
    root: dict[str, Any]


class Notification(BaseModel):
    op: Op
    ts_ms: int
    metadata: RecordUnknown | None = None
