# generated by datamodel-codegen:
#   filename:  ReloadHeader.yaml
#   timestamp: 2026-07-15T18:09:34+00:00

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import Field

from .Notification import Notification


class ReloadHeader(Notification):
    op: Literal['h']
    seq: Annotated[
        int, Field(description='The sequence number of last known source change')
    ]
