# generated by datamodel-codegen:
#   filename:  ReloadItem.yaml
#   timestamp: 2026-07-15T18:09:34+00:00

from __future__ import annotations

from typing import Literal

from .ChangePayload import ChangePayload
from .Notification import Notification


class ReloadItem(Notification):
    op: Literal['r']
    payload: ChangePayload
