# generated by datamodel-codegen:
#   filename:  ResultEvent.yaml
#   timestamp: 2026-07-15T18:09:33+00:00

from __future__ import annotations

from enum import Enum
from typing import Annotated, Any

from pydantic import BaseModel, Field, RootModel


class Kind(Enum):
    change = 'change'
    control = 'control'


class RecordUnknown(RootModel[dict[str, Any]]):
    root: dict[str, Any]


class ResultEvent(BaseModel):
    kind: Kind
    queryId: Annotated[
        str, Field(description='The ID of the query that the event originated from')
    ]
    sequence: Annotated[int, Field(description='The sequence number of the event')]
    sourceTimeMs: Annotated[
        int, Field(description='The time at which the source change was recorded')
    ]
    metadata: RecordUnknown | None = None
