# generated by datamodel-codegen:
#   filename:  RunningSignal.yaml
#   timestamp: 2024-11-22T20:54:00+00:00

from __future__ import annotations

from typing import Literal

from .ControlSignal import ControlSignal


class RunningSignal(ControlSignal):
    kind: Literal['running']
