# generated by datamodel-codegen:
#   filename:  RunningSignal.yaml
#   timestamp: 2026-07-15T18:09:33+00:00

from __future__ import annotations

from typing import Literal

from .ControlSignal import ControlSignal


class RunningSignal(ControlSignal):
    kind: Literal['running']
