# generated by datamodel-codegen:
#   filename:  UpdatePayload.yaml
#   timestamp: 2024-11-22T20:54:00+00:00

from __future__ import annotations

from typing import Any, Dict, Optional

from pydantic import BaseModel, Field, RootModel
from typing_extensions import Annotated


class RecordUnknown(RootModel[Optional[Dict[str, Any]]]):
    root: Optional[Dict[str, Any]] = None


class UpdatePayload(BaseModel):
    before: Annotated[
        RecordUnknown, Field(description='The snapshot of the result before the change')
    ]
    after: Annotated[
        RecordUnknown, Field(description='The snapshot of the result after the change')
    ]
