# generated by datamodel-codegen:
#   filename:  UpdatePayload.yaml
#   timestamp: 2026-07-15T18:09:33+00:00

from __future__ import annotations

from typing import Annotated, Any

from pydantic import BaseModel, Field, RootModel


class RecordUnknown(RootModel[dict[str, Any]]):
    root: dict[str, Any]


class UpdatePayload(BaseModel):
    before: Annotated[
        RecordUnknown, Field(description='The snapshot of the result before the change')
    ]
    after: Annotated[
        RecordUnknown, Field(description='The snapshot of the result after the change')
    ]
    groupingKeys: Annotated[
        list[str] | None,
        Field(
            description='The keys used to group or categorize this update, if applicable'
        ),
    ] = None
