# generated by datamodel-codegen:
#   filename:  Versions.yaml
#   timestamp: 2024-11-22T20:54:00+00:00

from __future__ import annotations

from enum import Enum


class Versions(Enum):
    v1 = 'v1'
