# generated by datamodel-codegen:
#   filename:  ViewItem.yaml
#   timestamp: 2026-07-15T18:09:33+00:00

from __future__ import annotations

from typing import Annotated

from pydantic import Field, RootModel

from .Data import Data
from .Header import Header


class ViewItem(RootModel[Header | Data]):
    root: Annotated[Header | Data, Field(title='ViewItem')]
