apiVersion: v1
kind: ContinuousQuery
name: query1
spec:
  mode: query
  sources:    
    subscriptions:
      - id: test-source
  query: > 
    MATCH 
      (p1:Person)-[:Knows]->(p2:Person)
    RETURN
      elementId(p1) as id1,
      p1.name as name1,
      p1.age as age1,
      elementId(p2) as id2,
      p2.name as name2,
      p2.age as age2