# Copyright 2024 The Drasi Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: ContinuousQuery
name: risky-containers
spec:
  mode: query
  sources:
    subscriptions:
      - id: k8s
        nodes:
          - sourceLabel: Pod
        pipeline:
          - extract-containers
      - id: devops
        nodes:
          - sourceLabel: RiskyImage
    joins:
      - id: HAS_IMAGE
        keys:
          - label: RiskyImage
            property: Image
          - label: Container
            property: image
    middleware:
      - kind: unwind
        name: extract-containers
        Pod:
          - selector: $.status.containerStatuses[*]
            label: Container
            key: $.containerID
            relation: OWNS

  query: >
    MATCH
      (p:Pod)-[:OWNS]->(c:Container)-[:HAS_IMAGE]->(i:RiskyImage)
    RETURN
      p.name as pod,
      c.image as image,
      c.name as name,
      c.ready as ready,
      c.started as started,
      c.restartCount as restartCount,
      i.Reason as reason
