[tool.poetry]
name = "advanced"
version = "0.1.0"
description = "advanced drasi python reaction"
authors = [""]

[tool.poetry.dependencies]
python = "^3.10"
drasi-reaction-sdk = {path = "../.."}
uvicorn = "^0.32.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
