apiVersion: apps/v1
kind: Deployment
metadata:
  name: gremlin-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gremlin-server
  template:
    metadata:
      labels:
        app: gremlin-server
    spec:
      containers:
      - name: gremlin-server
        image: tinkerpop/gremlin-server
        ports:
        - containerPort: 8182
---
apiVersion: v1
kind: Service
metadata:
  name: gremlin-server-service
spec:
  selector:
    app: gremlin-server
  ports:
    - protocol: TCP
      port: 8182
      targetPort: 8182
  type: LoadBalancer  # Use ClusterIP or NodePort if you don't want external access
