kind: Reaction
apiVersion: v1
name: post-dapr-pubsub
spec:
  kind: PostDaprPubSub
  queries:
    product-updates-packed: >
      {
        "pubsubName": "drasitest-pubsub",
        "topicName": "e2e-topic-packed",
        "format": "Packed",
        "skipControlSignals": false
      }
    product-updates-unpacked: >
      {
        "pubsubName": "drasitest-pubsub",
        "topicName": "e2e-topic-unpacked",
        "format": "Unpacked",
        "skipControlSignals": true
      }