apiVersion: v1
kind: Reaction
name: eventgrid-template-reaction
spec:
  kind: EventGrid-Test
  eventGridUri: http://eventgrid-emulator-svc.default.svc.cluster.local:8080/api/events
  eventGridSchema: CloudEvents
  format: template
  queries:
    product-updates-template:
      added: |
        {
          "eventType": "ProductAdded",
          "productId": {{after.product_id}},
          "name": "{{after.name}}",
          "description": "{{after.description}}",
          "price": {{after.price}}
        }
      updated: |
        {
          "eventType": "ProductUpdated",
          "productId": {{after.product_id}},
          "name": "{{after.name}}",
          "description": "{{after.description}}",
          "price": {{after.price}},
          "previousPrice": {{before.price}}
        }
      deleted: |
        {
          "eventType": "ProductDeleted",
          "productId": {{before.product_id}},
          "name": "{{before.name}}"
        }
