apiVersion: v1
kind: Reaction
name: eventgrid-template-reaction
spec:
  kind: EventGrid
  properties: 
    eventGridUri: http://eventgrid-emulator-svc.default.svc.cluster.local:8080/api/events
    eventGridSchema: CloudEvents
    format: template
  queries:
    product-updates-template: |
      added:
        template: |
          {
            "eventType": "ProductAdded",
            "productId": {{after.product_id}},
            "name": "{{after.name}}",
            "description": "{{after.description}}",
            "price": {{after.price}}
          }
        metadata:
          changeType: added
      updated:
        template: |
          {
            "eventType": "ProductUpdated",
            "productId": {{after.product_id}},
            "name": "{{after.name}}",
            "description": "{{after.description}}",
            "price": {{after.price}},
            "previousPrice": {{before.price}}
          }
        metadata:
          changeType: updated
      deleted:
        template: |
          {
            "eventType": "ProductDeleted",
            "productId": {{before.product_id}},
            "name": "{{before.name}}"
          }
        metadata:
          changeType: deleted

