apiVersion: v1
kind: ReactionProvider
name: EventGrid-Test
spec:
  services:
    reaction:
      image: reaction-eventgrid
  config_schema:
    type: object
    properties: 
      eventGridUri:
        type: string
      eventGridKey:
        type: string
      eventGridSchema:
        type: string
        enum:
          - "CloudEvents"
          - "EventGrid"
        default: "CloudEvents"
      format:
        type: string
        enum:
          - "packed"
          - "unpacked"
          - "template"
        default: "packed"
    required:
      - eventGridUri
