apiVersion: v1
kind: Source
name: eventgrid-test-source
spec:
  kind: PostgreSQL
  properties:
    host: eventgrid-test-db.default.svc.cluster.local
    port: 5432
    user: testuser
    password: testpassword
    database: testdb
    ssl: false
    tables:
      - public.product
