# generated by datamodel-codegen:
#   filename:  ChangeSource.json

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, Field, StrictInt, StrictStr


class ChangeSource(BaseModel):
    queryId: Annotated[StrictStr, Field(min_length=1, title='NonEmptyString')]
    ts_ms: Annotated[StrictInt, Field(ge=0, title='Timestamp')]
