# generated by datamodel-codegen:
#   filename:  DeletePayload.json

from __future__ import annotations

from typing import Any

from pydantic import BaseModel

from .ChangeSource import ChangeSource


class DeletePayload(BaseModel):
    source: ChangeSource
    before: dict[str, Any]
    after: Any | None = None
