# generated by datamodel-codegen:
#   filename:  DeleteEvent.json

from __future__ import annotations

from enum import Enum
from typing import Annotated, Literal

from pydantic import Field

from .DeletePayload import DeletePayload
from .RowEvent import RowEvent


class Op(Enum):
    i = 'i'
    u = 'u'
    d = 'd'


class DeleteEvent(RowEvent):
    op: Annotated[Literal['d'], Field(title='Operation')]
    payload: DeletePayload
