# generated by datamodel-codegen:
#   filename:  DeletePayload.json

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, ConfigDict

from .ChangeSource import ChangeSource


class DeletePayload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    source: ChangeSource
    before: dict[str, Any]
