# generated by datamodel-codegen:
#   filename:  InsertEvent.json

from __future__ import annotations

from enum import Enum
from typing import Annotated, Literal

from pydantic import Field

from .InsertPayload import InsertPayload
from .RowEvent import RowEvent


class Op(Enum):
    i = 'i'
    u = 'u'
    d = 'd'


class InsertEvent(RowEvent):
    op: Annotated[Literal['i'], Field(title='Operation')]
    payload: InsertPayload
