# generated by datamodel-codegen:
#   filename:  InsertPayload.json

from __future__ import annotations

from typing import Any

from pydantic import BaseModel

from .ChangeSource import ChangeSource


class InsertPayload(BaseModel):
    source: ChangeSource
    before: Any | None = None
    after: dict[str, Any]
