# generated by datamodel-codegen:
#   filename:  ListQueriesResponse.json

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import BaseModel, Field, StrictStr

from .NonEmptyString import NonEmptyString
from .Query import Query


class ListQueriesResponse(BaseModel):
    protocol_version: Literal[1]
    delivery_schema_version: Literal[1]
    router_id: Annotated[
        StrictStr, Field(min_length=1, pattern='^[^/\\s]+/[^/\\s]+$', title='RouterId')
    ]
    capabilities: Annotated[list[NonEmptyString], Field(min_length=1)]
    queries: list[Query]
