# generated by datamodel-codegen:
#   filename:  ListQueriesResponse.json

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import BaseModel, ConfigDict, Field, StrictStr

from .Query import Query


class ListQueriesResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    protocol_version: Literal[1]
    router_id: Annotated[
        StrictStr, Field(min_length=1, pattern='^[^/\\s]+/[^/\\s]+$', title='RouterId')
    ]
    queries: list[Query]
