# generated by datamodel-codegen:
#   filename:  NonEmptyString.json

from __future__ import annotations

from typing import Annotated

from pydantic import Field, RootModel, StrictStr


class NonEmptyString(RootModel[StrictStr]):
    root: Annotated[StrictStr, Field(min_length=1, title='NonEmptyString')]
