# generated by datamodel-codegen:
#   filename:  RowEvent.json

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, Field, StrictInt

from .Operation import Operation


class RowEvent(BaseModel):
    op: Operation
    seq: Annotated[StrictInt, Field(ge=0, title='Sequence')]
    ts_ms: Annotated[StrictInt, Field(ge=0, title='Timestamp')]
