# generated by datamodel-codegen:
#   filename:  SubscribeRequest.json

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field, StrictStr

from .Operation import Operation
from .Subscriber import Subscriber


class SubscribeRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    query_id: Annotated[StrictStr, Field(min_length=1, title='NonEmptyString')]
    operations: Annotated[list[Operation], Field(max_length=3, min_length=1)]
    subscriber: Subscriber
    subscription_incarnation: Annotated[
        StrictStr, Field(min_length=1, title='NonEmptyString')
    ]
