# generated by datamodel-codegen:
#   filename:  UnsubscribeResponse.json

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, Field, StrictBool, StrictStr


class UnsubscribeResponse(BaseModel):
    query_id: Annotated[StrictStr, Field(min_length=1, title='NonEmptyString')]
    removed: StrictBool
