# generated by datamodel-codegen:
#   filename:  UpdatePayload.json

from __future__ import annotations

from typing import Any

from pydantic import BaseModel

from .ChangeSource import ChangeSource


class UpdatePayload(BaseModel):
    source: ChangeSource
    before: dict[str, Any]
    after: dict[str, Any]
