# generated by datamodel-codegen:
#   filename:  UpdateEvent.json

from __future__ import annotations

from enum import Enum
from typing import Annotated, Literal

from pydantic import Field

from .RowEvent import RowEvent
from .UpdatePayload import UpdatePayload


class Op(Enum):
    i = 'i'
    u = 'u'
    d = 'd'


class UpdateEvent(RowEvent):
    op: Annotated[Literal['u'], Field(title='Operation')]
    payload: UpdatePayload
