/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type BootstrapStartedSignal = ControlSignal & {
  kind: "bootstrapStarted";
  [k: string]: unknown;
};

export interface ControlSignal {
  [k: string]: unknown;
}
