/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ChangeEvent = ResultEvent & {
  kind: "change";
  /**
   * The results that were added
   */
  addedResults: RecordUnknown1[];
  /**
   * The results that were updated
   */
  updatedResults: UpdatePayload[];
  /**
   * The results that were deleted
   */
  deletedResults: RecordUnknown1[];
  [k: string]: unknown;
};

export interface ResultEvent {
  queryId: string;
  sequence: string;
  sourceTimeMs: string;
  metadata?: RecordUnknown;
  [k: string]: unknown;
}
export interface RecordUnknown {
  [k: string]: unknown;
}
export interface RecordUnknown1 {
  [k: string]: unknown;
}
export interface UpdatePayload {
  before: RecordUnknown2;
  after: RecordUnknown3;
  [k: string]: unknown;
}
/**
 * The result before the change
 */
export interface RecordUnknown2 {
  [k: string]: unknown;
}
/**
 * The result after the change
 */
export interface RecordUnknown3 {
  [k: string]: unknown;
}
