/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * An event that represents a changes in the result set
 */
export type ChangeEvent = ResultEvent & {
  kind: "change";
  /**
   * The results that were added to the result set as a consequence of the change
   */
  addedResults: RecordUnknown1[];
  /**
   * The results that were updated on the result set as a consequence of the change
   */
  updatedResults: UpdatePayload[];
  /**
   * The results that were deleted from the result set as a consequence of the change
   */
  deletedResults: RecordUnknown1[];
  [k: string]: unknown;
};

export interface ResultEvent {
  kind: "change" | "control";
  /**
   * The ID of the query that the event originated from
   */
  queryId: string;
  /**
   * The sequence number of the event
   */
  sequence: number;
  /**
   * The time at which the source change was recorded
   */
  sourceTimeMs: number;
  metadata?: RecordUnknown;
  [k: string]: unknown;
}
export interface RecordUnknown {
  [k: string]: unknown;
}
export interface RecordUnknown1 {
  [k: string]: unknown;
}
/**
 * A payload that represents the before and after snapshots of a result
 */
export interface UpdatePayload {
  before: RecordUnknown2;
  after: RecordUnknown3;
  [k: string]: unknown;
}
/**
 * The snapshot of the result before the change
 */
export interface RecordUnknown2 {
  [k: string]: unknown;
}
/**
 * The snapshot of the result after the change
 */
export interface RecordUnknown3 {
  [k: string]: unknown;
}
