/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ControlEvent = ResultEvent & {
  kind: "control";
  controlSignal: ControlSignal;
  [k: string]: unknown;
};

export interface ResultEvent {
  queryId: string;
  sequence: string;
  sourceTimeMs: string;
  metadata?: RecordUnknown;
  [k: string]: unknown;
}
export interface RecordUnknown {
  [k: string]: unknown;
}
export interface ControlSignal {
  [k: string]: unknown;
}
