/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ResultEvent {
  /**
   * The ID of the query that the event originated from
   */
  queryId: string;
  /**
   * The sequence number of the event
   */
  sequence: string;
  /**
   * The time at which the source change was recorded
   */
  sourceTimeMs: string;
  metadata?: RecordUnknown;
  [k: string]: unknown;
}
export interface RecordUnknown {
  [k: string]: unknown;
}
