/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A signal that indicates that the query has stopped
 */
export type StoppedSignal = ControlSignal & {
  kind: "stopped";
  [k: string]: unknown;
};

export interface ControlSignal {
  kind: "bootstrapStarted" | "bootstrapCompleted" | "running" | "stopped" | "deleted";
  [k: string]: unknown;
}
