/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface UpdatePayload {
  before: RecordUnknown;
  after: RecordUnknown1;
  [k: string]: unknown;
}
/**
 * The result before the change
 */
export interface RecordUnknown {
  [k: string]: unknown;
}
/**
 * The result after the change
 */
export interface RecordUnknown1 {
  [k: string]: unknown;
}
