apiVersion: v1
kind: ReactionProvider
name: StoredProc
spec:
  config_schema: 
    type: object
    properties: 
      AddedResultCommand:
        type: string
      UpdatedResultCommand:
        type: string
      DeletedResultCommand:
        type: string
      DatabaseHostname:
        type: string
      DatabasePort:
        type: number
      DatabaseUser:
        type: string
      DatabaseDbname:
        type: string
      DatabasePassword:
        type: string
      DatabaseSsl:
        type: boolean
        default: false
    required:
      - DatabaseHostname
      - DatabasePort
      - DatabaseUser
      - DatabaseDbname
      - DatabasePassword
  services:
    storedproc:
      image: reaction-storedproc