apiVersion: v1
kind: Source
name: test-source-2
spec:
  kind: PostgreSQL
  properties:
    host: postgres.default.svc.cluster.local
    port: 5432
    user: test
    password: test
    database: test-db
    ssl: false
    tables:
      - public.Item
---
apiVersion: v1
kind: ContinuousQuery
name: query2
spec:
  mode: query
  sources:    
    subscriptions:
      - id: test-source-2
  query: > 
    MATCH 
      (i:Item {Category: '2'})
    RETURN 
      i.ItemId AS Id, 
      i.Name as Name,
      i.Category as Category