FROM --platform=$TARGETPLATFORM mcr.microsoft.com/dotnet/aspnet@sha256:38178966094e8ac38ac3377fa4195cbf63e9aef4030f5e62d2810f8a5df769e4 AS base
# mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/sdk@sha256:86fe223b90220ec8607652914b1d7dc56fc8ff422ca1240bb81e54c4b06509e6 AS build
# mcr.microsoft.com/dotnet/sdk:8.0
WORKDIR /src
COPY ["eventhub-reactivator.csproj", "."]
RUN dotnet restore "./eventhub-reactivator.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "eventhub-reactivator.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "eventhub-reactivator.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM ubuntu:22.04 AS final
RUN apt-get update && apt-get install -y bash curl dotnet-runtime-8.0 aspnetcore-runtime-8.0 && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "eventhub-reactivator.dll"]