FROM --platform=$TARGETPLATFORM mcr.microsoft.com/dotnet/aspnet@sha256:2b70ef1451cb01c2118969ad15fd0ae40fdbac158f09699fefae0dc32c4ca352 AS base
# mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/sdk@sha256:8c6beed050a602970c3d275756ed3c19065e42ce6ca0809f5a6fcbf5d36fd305 AS build
# mcr.microsoft.com/dotnet/sdk:8.0
WORKDIR /src
COPY ["eventhub-reactivator.csproj", "."]
RUN dotnet restore "./eventhub-reactivator.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "eventhub-reactivator.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "eventhub-reactivator.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM ubuntu:22.04 AS final
RUN apt-get update && apt-get install -y bash curl dotnet-runtime-8.0 aspnetcore-runtime-8.0 && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "eventhub-reactivator.dll"]