kind: Reaction
apiVersion: v1
name: sync-dapr-outputbinding
spec:
  kind: PostDaprOutputBinding
  queries:
    product-query: >
      {
        "bindingName": "product-outputbinding",
        "bindingType": "redis",
        "bindingOperation": "create",
        "bindingMetadataTemplate": {
          "key": "{{payload.after.product_name}}"
        },
        "packed": "Unpacked",
        "maxFailureCount": 5,
        "skipControlSignals": true
      }
    inventory-query: >
      {
        "bindingName": "inventory-outputbinding",
        "bindingType": "redis",
        "bindingOperation": "create",
        "bindingMetadataTemplate": {
          "key": "inventory"
        },
        "packed": "Unpacked",
        "maxFailureCount": 5,
        "skipControlSignals": true
      }