kind: Reaction
apiVersion: v1
name: sync-dapr-statestore
spec:
  kind: PostDaprOutputBinding
  queries:
    product-query: >
      {
        "bindingName": "product-outputbinding",
        "bindingType": "redis",
        "bindingOperation": "create",
        "bindingMetadata": {
          "key": "product"
        },
        "packed": "Unpacked",
        "maxFailureCount": 5,
        "skipControlSignals": false
      }
    inventory-query: >
      {
        "bindingName": "inventory-outputbinding",
        "bindingType": "redis",
        "bindingOperation": "create",
        "bindingMetadata": {
          "key": "inventory"
        },
        "packed": "Unpacked",
        "maxFailureCount": 5,
        "skipControlSignals": false
      }