[tool.poetry]
name = "simple"
version = "0.1.0"
description = "simple drasi python reaction"
authors = [""]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
drasi-reaction-sdk = "0.1.0a0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
