apiVersion: v1
kind: ReactionProvider
name: MCP
spec:
  services:
    reaction:
      image: reaction-mcp
      endpoints:
        gateway:
          setting: internal
          target: $port
      config_schema:
        type: object
        properties: 
          port:
            type: number
            default: 3000