name: Publish

on:
    workflow_dispatch:
      inputs:
        tag:
          description: 'Tag to publish'
          required: true
          default: 'latest'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Retag and push Docker images
        run: |
            IMAGE_NAMES=(
                "query-container-query-host"
                "query-container-publish-api"
                "query-container-view-svc"
                "api"
                "kubernetes-provider"
                "source-change-svc"
                "source-change-dispatcher"
                "source-query-api"
                "source-debezium-reactivator"
                "source-sql-proxy"
                "reaction-signalr"
            )

            for IMAGE_NAME in "${IMAGE_NAMES[@]}"; do
                REPO=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME

                docker pull $REPO:${{ github.sha }}
                docker tag $REPO:${{ github.sha }} $REPO:${{ github.ref_name }}
                docker push $REPO:${{ github.event.inputs.tag }}
            done
    
      - name: Logout from GitHub Container Registry
        run: docker logout ghcr.io
