name: Publish Artifacts

on:
  push:
    branches:
      - main

permissions:
  id-token: write # Required for requesting the JWT
  contents: read  # Required for actions/checkout


jobs:
  build-cli:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build
        working-directory: cli
        run: make

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: cli
          path: cli/bin
    
  publish_CLI:
    needs: build-cli
    runs-on: ubuntu-latest
    name: Publish ${{ matrix.os }}_${{ matrix.arch }} binaries
    environment: 
      name: github-actions
    strategy:
      matrix:
        include:
          - os: linux
            arch: arm64
          - os: linux
            arch: x64
          - os: darwin
            arch: arm64
          - os: darwin
            arch: x64
          - os: windows
            arch: x64
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Download binaries
        uses: actions/download-artifact@v4
    
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Upload the CLI installation scripts to Azure storage blob
        run: |
          az storage blob upload --file deploy/cli/install-drasi-cli-ghcr.sh --container-name installs-ghcr --overwrite --name install-drasi-cli-ghcr.sh --account-name drasi
          az storage blob upload --file deploy/cli/install.ps1 --container-name installs --overwrite --name install.ps1 --account-name drasi

      - name: Upload the CLI binaries to Azure storage blob  # Uploading to Azure storage blob  for now; We will switch to gh releases in the future
        run: |
            cd cli
            az storage blob upload-batch --account-name drasi --destination installs-ghcr --overwrite --source ${{ matrix.os }}-${{ matrix.arch }}/ --destination-path ${{ matrix.os }}-${{ matrix.arch }}/

  vscode_extension:
    name: Build and publish the VSCode vscode_extension
    runs-on: ubuntu-latest
    environment: 
      name: github-actions
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Building the extension
        run: |
          cd dev-tools/vscode/drasi
          npm install -g @vscode/vsce 
          npm install
          vsce package
      - name: Upload extension to storage blob
        run: | 
          cd dev-tools/vscode/drasi
          az storage blob upload --file drasi-0.0.3.vsix --container-name installs --overwrite --name drasi-0.0.3.vsix --account-name drasi