name: Publish

on:
    workflow_dispatch:

env:
  TAG_PREFIX: drasi/

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Install Skopeo
        run: |
          sudo apt-get update
          sudo apt-get install -y skopeo

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push OCI image to GHCR
        run: |
          skopeo copy --all oci:./query-container-query-host.tar docker://ghcr.io/${{ github.repository_owner }}/${{ env.TAG_PREFIX }}query-container-query-host:${{ github.head_ref }}
          skopeo copy --all oci:./query-container-publish-api.tar docker://ghcr.io/${{ github.repository_owner }}/${{ env.TAG_PREFIX }}query-container-publish-api:${{ github.head_ref }}
          skopeo copy --all oci:./query-container-view-svc.tar docker://ghcr.io/${{ github.repository_owner }}/${{ env.TAG_PREFIX }}query-container-view-svc:${{ github.head_ref }}
          skopeo copy --all oci:./api.tar docker://ghcr.io/${{ github.repository_owner }}/${{ env.TAG_PREFIX }}api:${{ github.head_ref }}
          skopeo copy --all oci:./kubernetes-provider.tar docker://ghcr.io/${{ github.repository_owner }}/${{ env.TAG_PREFIX }}kubernetes-provider:${{ github.head_ref }}
          skopeo copy --all oci:./source-change-svc.tar docker://ghcr.io/${{ github.repository_owner }}/${{ env.TAG_PREFIX }}source-change-svc:${{ github.head_ref }}
          skopeo copy --all oci:./source-change-dispatcher.tar docker://ghcr.io/${{ github.repository_owner }}/${{ env.TAG_PREFIX }}source-change-dispatcher:${{ github.head_ref }}
          skopeo copy --all oci:./source-query-api.tar docker://ghcr.io/${{ github.repository_owner }}/${{ env.TAG_PREFIX }}source-query-api:${{ github.head_ref }}
          skopeo copy --all oci:./source-debezium-reactivator.tar docker://ghcr.io/${{ github.repository_owner }}/${{ env.TAG_PREFIX }}source-debezium-reactivator:${{ github.head_ref }}
          skopeo copy --all oci:./reaction-signalr.tar docker://ghcr.io/${{ github.repository_owner }}/${{ env.TAG_PREFIX }}reaction-signalr:${{ github.head_ref }}

      - name: Logout from GitHub Container Registry
        run: docker logout ghcr.io
