# Copyright 2024 The Drasi Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Build and Publish Visual Studio Code Extension

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of the extension'
        required: true        


jobs:
    build-and-publish:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 18.x
            - name: Install VSCE
              run: npm install @vscode/vsce --save-dev
            - name: Install dependencies
              run: npm install
            - uses: lannonbr/vsce-action@4.0.0
              with:
                args: "publish -p $VSCE_TOKEN -v ${{ github.event.inputs.version }}"
              env:
                VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
            # - name: Build 
            #   run: vsce package
            # - name: Publish
            #   run: vsce publish -p ${{ secrets.VSCE_TOKEN }} -v ${{ github.event.inputs.version }} 

            